### ISSUE TITLE
Having issues with class in R2014b

### ISSUE THREAD

**Issue by ckj6** [KIOS-Research/EPANET-Matlab-Toolkit#3]
Hello!

Thank you for creating this helpful library. I'm having some issues loading it in R2014b, and have used the instructions in the README provided. However, when I run the `TEST.m` file, I get the following error:

```
Create EPANET Class
Error using loadlibrary (line 440)
The MATLAB program file describing your library could not be found, possible Perl or file system error.

Error in epanet>ENLoadLibrary (line 2341)
    loadlibrary('epanet2','epanet2.h')

Error in epanet/epanetLoadLibrary (line 388)
            [errcode] = ENLoadLibrary;

Error in epanet (line 236)
            [obj.errcode]=obj.epanetLoadLibrary;

Error in TEST (line 17)
d=epanet([inpname,'.inp']);
```

I haven't been able to use `loadlibrary` with `.h` files in this version of MATLAB, and my Googling indicates it is no longer available for this function. Do you have any ideas how I could get this class to work with R2014b? Your help is much appreciated!

**Comment by malikobaid** [comment]
Hi @ckj6 did you find a work around for this? i am having the same issues.

**Comment by eldemet** [comment]
Hi @malikobaid and @ckj6,

I'm not sure what causes this error; can you please try the newer version of the [Epanet Matlab Class v2.00.00](https://github.com/KIOS-Research/EPANET-Matlab-Class/tree/Version-2.0-) to see if the error is still there? 

We've used it successfully with the 2015 version of Matlab (windows x64).

Thanks

Demetrios

**Comment by malikobaid** [comment]
Hi @eldemet  with the newer version you mentioned i am getting the following error

Warning: File "epanet20012x64" is not a valid win application. 
> In epanet (line 458)
  In Example_CompareEpanet20012Epanet20013dll (line 14) 
Error using calllib
Library was not found

Error in epanet>ENgetcount (line 6512)
    [errcode,count]=calllib(libepanet,'ENgetcount',countcode,0);

Error in epanet/getNodeCount (line 776)
            [obj.errcode, value] = ENgetcount(0,obj.libepanet);

Error in epanet/getNodeTankDiameter (line 1344)
            value=zeros(1,obj.getNodeCount);

Error in Example_CompareEpanet20012Epanet20013dll (line 15)
a=d.getNodeTankDiameter;

Obaid

**Comment by eldemet** [comment]
@malikobaid 

1. Can you please mention the operating system and computer architecture you are using?
2. Can you please try running this command while in the new folder: loadlibrary('epanet20012x64.dll','epanet20012x64.h')

**Comment by malikobaid** [comment]
<img width="1221" alt="screen shot 2015-07-30 at 16 23 06" src="https://cloud.githubusercontent.com/assets/974229/8987120/5741ac2a-36d7-11e5-90ec-dd4049deae21.png">

I am using matlab 2015a x64

running the commands i get the following error:
>> loadlibrary('epanet20012x64.dll','epanet20012x64.h')
Index exceeds matrix dimensions.
Error in loadlibrary>getLoadlibraryCompilerConfiguration (line 527)
Error in loadlibrary (line 263)

**Comment by eldemet** [comment]
Ok. Interesting, never seen this error before. I have almost the same setup.

Which C compiler are you using for matlab?

e.g 
>> mex -setup
MEX configured to use 'Microsoft Windows SDK 7.1 (C)' for C language compilation.

**Comment by malikobaid** [comment]
Thanks alot for the quick replies and support
I updated my windows and installed Microsoft Windows SDK 7.1. That seems to work.
Is there any documentation for the wrappers or are the functions calls are the same as the EPANET Programmers kit.

Also i am getting this warning :

Warning: The data type 'FcnPtr' used by function ENepanet does not exist. 
> In loadlibrary (line 431)
  In epanet>ENLoadLibrary (line 6657)
  In epanet (line 486)
  In Example_ReplacePumpWithPipe (line 5) 

Obaid

**Comment by eldemet** [comment]
Hi @malikobaid, this is warning which always appears when loading the library, but it does not affect the solutions nor the Class
