### ISSUE TITLE
Error While trying to load NodeCoordinates in Epanet/Matlab

### ISSUE THREAD

**Issue by Alexandroz** [KIOS-Research/EPANET-Matlab-Toolkit#6]
Hi,
I am using the latest version of Epanet-Matlab Class Master and Matlab R2015a. When i am trying to load the d.getNodeCoordinates command i get this error:

Error using fopen
File identifier must be an integer-valued scalar of type
double.

Error in epanet>readAllFile (line 8194)
fid = fopen(inpname, 'rt');%or msxname

Error in epanet/readInpFile (line 5683)
[info,tline,allines] =
readAllFile(obj.Bintempfile);

Error in epanet/getNodeCoordinates (line 6041)
[~,info] = obj.readInpFile;

I am not sure but a relevant error is generated while i am trying to use the d.plot commands.Which is the following:

Error using fopen
File identifier must be an integer-valued scalar of type
double.

Error in epanet>readAllFile (line 8194)
fid = fopen(inpname, 'rt');%or msxname

Error in epanet/readInpFile (line 5683)
[info,tline,allines] =
readAllFile(obj.Bintempfile);

Error in epanet/getNodeCoordinates (line 6041)
[~,info] = obj.readInpFile;

Error in epanet>ENplot (line 7922)
v.nodecoords=obj.getNodeCoordinates;

Error in epanet/plot (line 721)
[value] = ENplot(obj,'bin',0,varargin{:});

Thank you.

**Comment by Mariosmsk** [comment]
The epanet file is loaded? Maybe returns a warning if not loaded.
The following example is working? 
Example:
d=epanet('networks/Net1_Rossman2000.inp');
d.plot

**Comment by Alexandroz** [comment]
Hi
Marios i have tried the following example but i get the same error:
Error using fopen
File identifier must be an integer-valued scalar of type
double.

Error in epanet>readAllFile (line 8194)
    fid = fopen(inpname, 'rt');%or msxname

Error in epanet/readInpFile (line 5683)
                [info,tline,allines] =
                readAllFile(obj.Bintempfile);

Error in epanet/getNodeCoordinates (line 6041)
            [~,info] = obj.readInpFile;

Error in epanet>ENplot (line 7922)
        v.nodecoords=obj.getNodeCoordinates;

Error in epanet/plot (line 721)
            [value] = ENplot(obj,'bin',0,varargin{:});
 
I load the epanet file and everything else works perfect but when i am trying to load the coordinates and the plot i get those errors..

**Comment by Mariosmsk** [comment]
Could you send me the input file that you used?
