### ISSUE TITLE
Problems in using the function 'd.setNodeSourceQuality'

### ISSUE THREAD

**Issue by Chaowang1990** [KIOS-Research/EPANET-Matlab-Toolkit#7]
Hi,

I am using this EPANET-Matlab toolkit to simulate the network in the example.

The function I want to realize is to inject contamination at different nodes with different contamination pattern. My idea is to get the node source quality and node source pattern index and set the values of them. 

However, when I set the value with two functions: 'd.setNodeSourceQuality' and 'd.setNodeSourcePatternIndex', I cannot set them in the desired nodes I want. For example, I use the code as follows:

values = d.getNodeSourceQuality %%suppose this line give the result as: NaN NaN NaN NaN NaN NaN 
values(6)=0.5; %% Here is just an example, actually values(any position)=0.5 will result in the same result.
d.setNodeSourceQuality(values)
d.getNodeSourceQuality

The result I want is NaN NaN NaN NaN NaN 0.5. However, the code results in: 0.5 NaN NaN NaN NaN NaN.

This means I can just set the value from the very starting position. I know I can set the value one by one until reach the position I want, and then modify the proceeding ones to get the result I want. But is there any direct way to solve this problem?

Thank you.

Chao Wang

**Comment by Mariosmsk** [comment]
Hi Chao Wang, 

Thank you for your comment. Please download the revised [epanet.m](https://raw.githubusercontent.com/KIOS-Research/EPANET-Matlab-Toolkit/master/epanet.m), try again and inform me if is it ok.

Thank you.
Marios

**Comment by Chaowang1990** [comment]
Hi Mariosmsk,

Thanks for your update. Now it works.

Thank you.

Chao
