### ISSUE TITLE
Problem loading libraries

### ISSUE THREAD

**Issue by svnacho** [KIOS-Research/EPANET-Matlab-Toolkit#8]
I don't know why I can't load epanet2.dll and epanet2.h in my Matlab R2014a. I've checked my Matlab version and it's 64-bit, so I'm running Matlab in some folder with only these 64-bit files. However, loadlibrary() just shows me this error:

```
>> loadlibrary('epanet2','epanet2.h');
Index exceeds matrix dimensions.

Error in loadlibrary>getLoadlibraryCompilerConfiguration (line 497)
        compilerConfiguration=compilerConfiguration(1);  %unix machines return c and cpp compilers here

Error in loadlibrary (line 253)
    [thunk_build_fn,preprocess_command]=getLoadlibraryCompilerConfiguration(ccinclude,header,headername,compilerConfiguration); 
>> 
```
What should I do?

Thank you. I'm a begginer!

**Comment by Mariosmsk** [comment]
Hi svnacho, 

Maybe you need to run "mex -setup" and select compiler (e.g. Microsoft Windows SDK 7.1).
